import { Router } from 'express';
import { authRouter } from '../modules/auth/auth.routes';
import { usersRouter } from '../modules/users/users.routes';
import { rolesRouter } from '../modules/roles/roles.routes';
import { auditRouter } from '../modules/audit/audit.routes';
import { settingsRouter, currenciesRouter } from '../modules/settings/settings.routes';
import { dashboardRouter } from '../modules/dashboard/dashboard.routes';
import { leadsRouter } from '../modules/leads/leads.routes';
import { customersRouter } from '../modules/customers/customers.routes';
import { followUpsRouter } from '../modules/followups/followups.routes';
import { countriesRouter } from '../modules/countries/countries.routes';
import { visaTypesRouter } from '../modules/visa-types/visa-types.routes';
import { applicationsRouter } from '../modules/applications/applications.routes';
import { appointmentsRouter } from '../modules/appointments/appointments.routes';
import { suppliersRouter } from '../modules/suppliers/suppliers.routes';
import { agentsRouter } from '../modules/agents/agents.routes';
import { flightsRouter } from '../modules/flights/flights.routes';
import { hotelsRouter } from '../modules/hotels/hotels.routes';
import { packagesRouter } from '../modules/packages/packages.routes';
import { bookingsRouter } from '../modules/bookings/bookings.routes';
import { quotationsRouter } from '../modules/quotations/quotations.routes';
import { invoicesRouter } from '../modules/invoices/invoices.routes';
import { paymentsRouter } from '../modules/payments/payments.routes';
import { expensesRouter } from '../modules/expenses/expenses.routes';
import { commissionsRouter } from '../modules/commissions/commissions.routes';
import { documentsRouter } from '../modules/documents/documents.routes';
import { communicationsRouter } from '../modules/communications/communications.routes';
import { reportsRouter } from '../modules/reports/reports.routes';
import { airportsRouter } from '../modules/airports/airports.routes';
import { airlinesRouter } from '../modules/airlines/airlines.routes';
import { flightFaresRouter } from '../modules/flight-fares/flight-fares.routes';

export const apiRouter = Router();

apiRouter.use('/auth', authRouter);
apiRouter.use('/users', usersRouter);
apiRouter.use('/roles', rolesRouter);
apiRouter.use('/audit-logs', auditRouter);
apiRouter.use('/settings', settingsRouter);
apiRouter.use('/currencies', currenciesRouter);
apiRouter.use('/dashboard', dashboardRouter);
apiRouter.use('/leads', leadsRouter);
apiRouter.use('/customers', customersRouter);
apiRouter.use('/follow-ups', followUpsRouter);
apiRouter.use('/countries', countriesRouter);
apiRouter.use('/visa-types', visaTypesRouter);
apiRouter.use('/applications', applicationsRouter);
apiRouter.use('/appointments', appointmentsRouter);
apiRouter.use('/suppliers', suppliersRouter);
apiRouter.use('/agents', agentsRouter);
apiRouter.use('/flights', flightsRouter);
apiRouter.use('/hotels', hotelsRouter);
apiRouter.use('/packages', packagesRouter);
apiRouter.use('/bookings', bookingsRouter);
apiRouter.use('/quotations', quotationsRouter);
apiRouter.use('/invoices', invoicesRouter);
apiRouter.use('/payments', paymentsRouter);
apiRouter.use('/expenses', expensesRouter);
apiRouter.use('/commissions', commissionsRouter);
apiRouter.use('/documents', documentsRouter);
apiRouter.use('/communications', communicationsRouter);
apiRouter.use('/reports', reportsRouter);
apiRouter.use('/airports', airportsRouter);
apiRouter.use('/airlines', airlinesRouter);
apiRouter.use('/flight-fares', flightFaresRouter);
